import { Destination } from "./types";

export const destinations: Destination[] = [
  {
    slug: "colombo",
    name: "Colombo",
    lat: 6.9271,
    lng: 79.8612,
    district: "Colombo",
    province: "Western",
    description: "Sri Lanka's vibrant capital city, a melting pot of cultures with colonial architecture, buzzing markets, and seaside promenades.",
    longDescription: "Colombo is the commercial capital of Sri Lanka, offering a blend of modern skyscrapers and colonial-era buildings. From the iconic Gangaramaya Temple to the bustling Pettah Market, the city pulses with energy. The Galle Face Green provides a perfect sunset spot along the Indian Ocean, while Colombo's restaurant scene showcases the island's incredible cuisine.",
    category: "cultural",
    image: "/images/colombo.webp",
    attractions: ["Gangaramaya Temple", "Galle Face Green", "Pettah Market", "National Museum", "Colombo Lotus Tower", "Beira Lake"],
    activities: ["City walking tours", "Street food exploration", "Temple visits", "Shopping", "Coastal dining"],
    emergencyContacts: [
      { name: "Police Emergency", number: "119", type: "police" },
      { name: "National Hospital", number: "+94 11 269 1111", type: "hospital" },
    ],
    hospitals: ["National Hospital of Sri Lanka", "Lanka Hospital", "Asiri Central Hospital"],
    bestTimeToVisit: "January to April",
    elevation: 0,
  },
  {
    slug: "kandy",
    name: "Kandy",
    lat: 7.2906,
    lng: 80.6337,
    district: "Kandy",
    province: "Central",
    description: "The cultural capital, home to the sacred Temple of the Tooth Relic, surrounded by misty hills and lush tea estates.",
    longDescription: "Kandy, a UNESCO World Heritage Site, sits in the heart of Sri Lanka's hill country. The city is built around a serene lake and is home to the revered Temple of the Tooth Relic, which houses a tooth of the Buddha. The annual Esala Perahera festival transforms the city into a spectacular celebration with elephants, dancers, and drummers.",
    category: "cultural",
    image: "/images/kandy.webp",
    attractions: ["Temple of the Tooth", "Kandy Lake", "Royal Botanical Gardens", "Bahiravakanda Temple", "Udawatta Kele Sanctuary"],
    activities: ["Temple visits", "Cultural shows", "Botanical garden walks", "Tea estate tours", "Lake strolls"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Kandy General Hospital", number: "+94 81 222 2261", type: "hospital" },
    ],
    hospitals: ["Kandy General Hospital", "Lanka Hospital Kandy"],
    bestTimeToVisit: "January to April",
    elevation: 465,
  },
  {
    slug: "ella",
    name: "Ella",
    lat: 6.8667,
    lng: 81.0466,
    district: "Badulla",
    province: "Uva",
    description: "A charming hill town famous for the Nine Arch Bridge, stunning viewpoints, and the most scenic train ride in the world.",
    longDescription: "Ella is a tiny paradise nestled in Sri Lanka's southern hill country. This small town has become a backpacker haven thanks to its breathtaking scenery, including the iconic Nine Arch Bridge, Little Adam's Peak, and Ella Rock. The train journey from Kandy to Ella is often cited as one of the most beautiful rail journeys in the world, passing through tea plantations, misty mountains, and lush valleys.",
    category: "hill-country",
    image: "/images/ella.webp",
    attractions: ["Nine Arch Bridge", "Little Adam's Peak", "Ella Rock", "Ravana Falls", "Demodara Loop"],
    activities: ["Hiking", "Train spotting", "Tea plantation tours", "Waterfall visits", "Zip-lining"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Badulla Hospital", number: "+94 55 222 2261", type: "hospital" },
    ],
    hospitals: ["Badulla General Hospital", "Ella Rural Hospital"],
    bestTimeToVisit: "February to April",
    elevation: 1041,
  },
  {
    slug: "sigiriya",
    name: "Sigiriya",
    lat: 7.957,
    lng: 80.7603,
    district: "Matale",
    province: "Central",
    description: "The ancient Lion Rock fortress, a UNESCO World Heritage Site rising dramatically from the surrounding jungle.",
    longDescription: "Sigiriya, or Lion Rock, is one of Sri Lanka's most iconic landmarks. This 5th-century rock fortress rises 200 meters above the surrounding plains and features ancient frescoes, the mirror wall, and the massive lion's paw gateway. The summit offers panoramic views of the surrounding jungle and distant mountains. Nearby, the Pidurangala Rock offers an equally stunning but less crowded alternative viewpoint.",
    category: "cultural",
    image: "/images/sigiriya.webp",
    attractions: ["Sigiriya Rock Fortress", "Pidurangala Rock", "Sigiriya Museum", "Sigiriya Frescoes", "Water Gardens"],
    activities: ["Rock climbing", "Archaeological exploration", "Photography", "Village cycling", "Safari"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Dambulla Hospital", number: "+94 66 228 4731", type: "hospital" },
    ],
    hospitals: ["Dambulla Base Hospital"],
    bestTimeToVisit: "January to April",
    elevation: 349,
  },
  {
    slug: "galle",
    name: "Galle",
    lat: 6.0535,
    lng: 80.22,
    district: "Galle",
    province: "Southern",
    description: "A historic coastal city known for its stunning Dutch fort, charming streets, and beautiful southern beaches.",
    longDescription: "Galle is a gem on Sri Lanka's southern coast, renowned for its UNESCO-listed Galle Fort built by the Dutch in the 17th century. Inside the fort walls, you'll find boutique hotels, art galleries, quirky shops, and cafes lining cobblestone streets. The city blends colonial architecture with tropical vibes, and nearby beaches like Unawatuna and Jungle Beach are perfect for swimming and snorkeling.",
    category: "beach",
    image: "/images/galle.webp",
    attractions: ["Galle Fort", "Dutch Reformed Church", "Lighthouse", "Jungle Beach", "Unawatuna Beach", "Maritime Museum"],
    activities: ["Fort walking tour", "Beach days", "Snorkeling", "Surfing", "Whale watching"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Karapitiya Hospital", number: "+94 91 223 4801", type: "hospital" },
    ],
    hospitals: ["Karapitiya Teaching Hospital", "Mahamodara Hospital"],
    bestTimeToVisit: "December to April",
    elevation: 0,
  },
  {
    slug: "mirissa",
    name: "Mirissa",
    lat: 5.9483,
    lng: 80.4589,
    district: "Matara",
    province: "Southern",
    description: "A laid-back beach paradise known for whale watching, golden sand, and breathtaking sunsets.",
    longDescription: "Mirissa is one of Sri Lanka's most popular beach destinations. This small town offers a perfect blend of relaxation and adventure. It's one of the best places in the world for blue whale and sperm whale watching from November to April. The crescent-shaped beach is ideal for swimming and surfing, and the iconic Parrot Rock provides stunning sunset viewpoints.",
    category: "beach",
    image: "/images/mirissa.webp",
    attractions: ["Mirissa Beach", "Parrot Rock", "Coconut Tree Hill", "Secret Beach", "Whale Watching Point"],
    activities: ["Whale watching", "Surfing", "Snorkeling", "Beach yoga", "Sunset photography"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Matara Hospital", number: "+94 41 222 2261", type: "hospital" },
    ],
    hospitals: ["Matara General Hospital"],
    bestTimeToVisit: "November to April",
    elevation: 0,
  },
  {
    slug: "nuwara-eliya",
    name: "Nuwara Eliya",
    lat: 6.9497,
    lng: 80.7891,
    district: "Nuwara Eliya",
    province: "Central",
    description: "Known as 'Little England', this hill station offers cool climates, tea plantations, and colonial charm.",
    longDescription: "Nuwara Eliya is a picturesque hill station at 1,868 meters elevation, known for its cool climate and colonial-era bungalows. The town is surrounded by tea plantations, and visitors can tour factories to learn about Ceylon tea production. Gregory Lake provides boat rides, while Horton Plains National Park offers the famous World's End cliff viewpoint.",
    category: "hill-country",
    image: "/images/nuwara-eliya.webp",
    attractions: ["Horton Plains", "World's End", "Gregory Lake", "Hakgala Botanical Garden", "Pedro Tea Estate", "Victoria Park"],
    activities: ["Tea plantation tours", "Hiking at Horton Plains", "Boating", "Golf", "Strawberry picking"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "District Hospital", number: "+94 52 222 2261", type: "hospital" },
    ],
    hospitals: ["Nuwara Eliya District Hospital"],
    bestTimeToVisit: "February to April",
    elevation: 1868,
  },
  {
    slug: "yala",
    name: "Yala National Park",
    lat: 6.3798,
    lng: 81.5189,
    district: "Hambantota",
    province: "Southern",
    description: "Sri Lanka's most famous national park, home to the highest density of leopards in the world.",
    longDescription: "Yala National Park is Sri Lanka's premier wildlife sanctuary, covering nearly 1,000 square kilometers of scrubland, lagoons, and coastline. It boasts the highest density of leopards in the world, along with elephants, sloth bears, crocodiles, and over 200 bird species. Safari jeep tours depart at dawn for the best wildlife sightings.",
    category: "wildlife",
    image: "/images/yala.webp",
    attractions: ["Block 1 Safari Zone", "Sithulpawwa Rock Temple", "Yala Beach", "Elephant Gathering Points", "Leopard Territory"],
    activities: ["Jeep safari", "Bird watching", "Photography", "Camping", "Beach visits"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Hambantota Hospital", number: "+94 47 222 0261", type: "hospital" },
    ],
    hospitals: ["Hambantota District Hospital", "Tissamaharama Hospital"],
    bestTimeToVisit: "February to July",
    elevation: 30,
  },
  {
    slug: "trincomalee",
    name: "Trincomalee",
    lat: 8.5874,
    lng: 81.2152,
    district: "Trincomalee",
    province: "Eastern",
    description: "An east coast gem with natural harbors, pristine beaches, and ancient Hindu temples.",
    longDescription: "Trincomalee sits on one of the world's finest natural harbors on Sri Lanka's northeastern coast. The city offers a mix of history and natural beauty, from the ancient Koneswaram Temple perched on Swami Rock to the turquoise waters of Nilaveli and Marble Beach. Pigeon Island nearby offers excellent snorkeling with coral reefs and reef sharks.",
    category: "beach",
    image: "/images/trincomalee.webp",
    attractions: ["Koneswaram Temple", "Nilaveli Beach", "Pigeon Island", "Marble Beach", "Fort Frederick", "Hot Springs"],
    activities: ["Snorkeling", "Diving", "Whale watching", "Temple visits", "Beach relaxation"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Trincomalee Hospital", number: "+94 26 222 2261", type: "hospital" },
    ],
    hospitals: ["Trincomalee General Hospital"],
    bestTimeToVisit: "May to September",
    elevation: 0,
  },
  {
    slug: "anuradhapura",
    name: "Anuradhapura",
    lat: 8.3114,
    lng: 80.4037,
    district: "Anuradhapura",
    province: "North Central",
    description: "One of the ancient capitals of Sri Lanka, a sacred Buddhist pilgrimage city with thousand-year-old ruins.",
    longDescription: "Anuradhapura was the first capital of ancient Sri Lanka and remains one of the most sacred Buddhist sites in the world. The city's ruins span over 40 square kilometers and include massive dagobas (stupas), ancient monasteries, and the Sri Maha Bodhi tree - said to be the oldest documented tree in the world, grown from a cutting of the tree under which Buddha achieved enlightenment.",
    category: "cultural",
    image: "/images/anuradhapura.webp",
    attractions: ["Sri Maha Bodhi", "Ruwanwelisaya", "Jetavanaramaya", "Abhayagiri Dagoba", "Isurumuniya", "Twin Ponds"],
    activities: ["Cycling tours", "Temple visits", "Archaeological exploration", "Photography", "Meditation"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Teaching Hospital", number: "+94 25 222 2261", type: "hospital" },
    ],
    hospitals: ["Anuradhapura Teaching Hospital"],
    bestTimeToVisit: "January to April",
    elevation: 89,
  },
  {
    slug: "polonnaruwa",
    name: "Polonnaruwa",
    lat: 7.9403,
    lng: 81.0188,
    district: "Polonnaruwa",
    province: "North Central",
    description: "The medieval capital of Sri Lanka, featuring well-preserved ruins and the famous Gal Vihara rock sculptures.",
    longDescription: "Polonnaruwa was the second capital of ancient Sri Lanka and is a UNESCO World Heritage Site. The well-preserved ruins include the Royal Palace, the Audience Hall, and the stunning Gal Vihara - a group of four magnificent Buddha statues carved from a single granite rock face. The ancient city is best explored by bicycle, with ruins spread across a compact, well-maintained archaeological park.",
    category: "cultural",
    image: "/images/polonnaruwa.webp",
    attractions: ["Gal Vihara", "Royal Palace", "Parakrama Samudra", "Vatadage", "Lankatilaka", "Rankoth Vehera"],
    activities: ["Cycling tours", "Archaeological exploration", "Photography", "Lake visits", "Museum tours"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "District Hospital", number: "+94 27 222 2261", type: "hospital" },
    ],
    hospitals: ["Polonnaruwa District Hospital"],
    bestTimeToVisit: "January to April",
    elevation: 60,
  },
  {
    slug: "dambulla",
    name: "Dambulla",
    lat: 7.856,
    lng: 80.6522,
    district: "Matale",
    province: "Central",
    description: "Home to the remarkable cave temple complex, a UNESCO World Heritage Site with over 150 Buddha statues.",
    longDescription: "The Dambulla Cave Temple is the largest and best-preserved cave temple complex in Sri Lanka. Dating back to the 1st century BC, the five caves contain over 150 Buddha statues and stunning ceiling murals covering an area of 2,100 square meters. The golden Buddha statue at the base of the rock is a modern addition that serves as a museum entrance.",
    category: "cultural",
    image: "/images/dambulla.webp",
    attractions: ["Cave Temple Complex", "Golden Temple", "Rangiri Dambulla Stadium", "Iron Wood Forest", "Rose Quartz Mountain"],
    activities: ["Temple exploration", "Photography", "Hiking", "Village tours", "Spice garden visits"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Dambulla Hospital", number: "+94 66 228 4731", type: "hospital" },
    ],
    hospitals: ["Dambulla Base Hospital"],
    bestTimeToVisit: "January to April",
    elevation: 340,
  },
  {
    slug: "bentota",
    name: "Bentota",
    lat: 6.4214,
    lng: 79.9977,
    district: "Galle",
    province: "Southern",
    description: "A popular beach resort town known for water sports, river safaris, and luxury beachfront hotels.",
    longDescription: "Bentota is one of Sri Lanka's most popular beach resort towns, located on the southwestern coast. The town offers a perfect mix of golden sandy beaches, water sports, and river experiences. The Bentota River provides opportunities for boat safaris to see crocodiles, water monitors, and exotic birds. The Brief Garden, designed by renowned architect Geoffrey Bawa, is a nearby cultural highlight.",
    category: "beach",
    image: "/images/bentota.webp",
    attractions: ["Bentota Beach", "Brief Garden", "Bentota River", "Sea Turtle Hatchery", "Lunuganga Estate"],
    activities: ["Water sports", "River safari", "Surfing", "Spa treatments", "Garden tours"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Karapitiya Hospital", number: "+94 91 223 4801", type: "hospital" },
    ],
    hospitals: ["Karapitiya Teaching Hospital"],
    bestTimeToVisit: "November to April",
    elevation: 0,
  },
  {
    slug: "arugam-bay",
    name: "Arugam Bay",
    lat: 6.8406,
    lng: 81.8372,
    district: "Ampara",
    province: "Eastern",
    description: "World-class surfing destination on the east coast, famous for its point break and laid-back vibes.",
    longDescription: "Arugam Bay is Sri Lanka's premier surfing destination, consistently ranked among the world's top surf spots. The main point break offers perfect right-hand waves from April to October. Beyond surfing, the area offers incredible wildlife viewing at nearby Kumana National Park, ancient temples, and pristine lagoons. The laid-back atmosphere makes it a favorite among backpackers and surf enthusiasts.",
    category: "adventure",
    image: "/images/arugam-bay.webp",
    attractions: ["Main Point Break", "Whiskey Point", "Peanut Farm", "Kumana National Park", "Muhudu Maha Viharaya", "Pottuvil Lagoon"],
    activities: ["Surfing", "Safari", "Lagoon kayaking", "Temple visits", "Beach yoga"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Ampara Hospital", number: "+94 63 222 2261", type: "hospital" },
    ],
    hospitals: ["Ampara General Hospital"],
    bestTimeToVisit: "April to October",
    elevation: 0,
  },
  {
    slug: "adams-peak",
    name: "Adam's Peak",
    lat: 6.8096,
    lng: 80.4994,
    district: "Ratnapura",
    province: "Sabaragamuwa",
    description: "The sacred mountain with the 'Sri Pada' footprint, a pilgrimage site revered by multiple religions.",
    longDescription: "Adam's Peak (Sri Pada) is a 2,243-meter mountain sacred to Buddhists, Hindus, Muslims, and Christians alike. At the summit is a rock formation known as the Sacred Footprint. The traditional pilgrimage season runs from December to May, with climbers ascending through the night to witness the spectacular sunrise from the summit and the rare triangular shadow phenomenon.",
    category: "adventure",
    image: "/images/adams-peak.webp",
    attractions: ["Sacred Footprint", "Sunrise Viewpoint", "Shadow Triangle", "Seetha Gangula Waterfall", "Wilderness Sanctuary"],
    activities: ["Night hiking", "Sunrise watching", "Photography", "Pilgrimage", "Nature walks"],
    emergencyContacts: [
      { name: "Police", number: "119", type: "police" },
      { name: "Ratnapura Hospital", number: "+94 45 222 2261", type: "hospital" },
    ],
    hospitals: ["Ratnapura General Hospital"],
    bestTimeToVisit: "December to May",
    elevation: 2243,
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export function getDestinationsByCategory(category: string): Destination[] {
  if (category === "all") return destinations;
  return destinations.filter((d) => d.category === category);
}

export const CATEGORIES = [
  { value: "all", label: "All Destinations", icon: "🗺️" },
  { value: "beach", label: "Beach", icon: "🏖️" },
  { value: "hill-country", label: "Hill Country", icon: "⛰️" },
  { value: "cultural", label: "Cultural", icon: "🏛️" },
  { value: "wildlife", label: "Wildlife", icon: "🐘" },
  { value: "adventure", label: "Adventure", icon: "🏄" },
];
